eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

jwt:
  secret: ${JWT_SECRET}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

logging:
  level:
    root: WARN

