server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    default: dev

  #Here we will define the routes for our gateway,
  # We are using Eureka for service discovery,
  # but we still need to define routes in API Gateway.
  # Eureka helps resolve service names (lb://SERVICE-NAME)
  # to actual instances, but routing rules must be defined here.
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/api/auth/**
        #Just for the testing purpose, we are routing user-service to authservice, but in real application it should be routed to user-service
        - id: user-service
          uri: lb://authservice
          predicates:
            - Path=/api/users/**
        - id: admin-service
          uri: lb://adminservice
          predicates:
            - Path=/api/admin/**

        - id: catalog-service
          uri: lb://catalogservice
          predicates:
            - Path=/api/catalog/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/cart/**, /api/checkout/**, /api/orders/**

        - id: payment-service
          uri: lb://paymentservice
          predicates:
            - Path=/api/payments/internal/**


eureka:
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0

