server:
  port: 8085

spring:
  application:
    name: adminservice
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

# Eureka Config
eureka:
  instance:
    prefer-ip-address: true

# Feign Config
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0

