server:
  port: 8084

spring:
  application:
    name: paymentservice
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: ""
      password: ""
eureka:
  instance:
    prefer-ip-address: true

payment:
  currency: INR

management:
  tracing:
    sampling:
      probability: 1.0

