server:
  port: 8081

spring:
  application:
    name: authservice
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true

jwt:
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 1.0

